[2022-06-01 19:42:42,536] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-06-01T19:42:32.026131+00:00 [queued]>
[2022-06-01 19:42:42,548] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-06-01T19:42:32.026131+00:00 [queued]>
[2022-06-01 19:42:42,549] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 19:42:42,549] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-01 19:42:42,549] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 19:42:42,567] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-06-01 19:42:32.026131+00:00
[2022-06-01 19:42:42,575] {standard_task_runner.py:52} INFO - Started process 115 to run task
[2022-06-01 19:42:42,580] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2022-06-01T19:42:32.026131+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpc9_vlyh9', '--error-file', '/tmp/tmp8se2u5mb']
[2022-06-01 19:42:42,581] {standard_task_runner.py:77} INFO - Job 118: Subtask local_to_gcs_task
[2022-06-01 19:42:42,644] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-06-01T19:42:32.026131+00:00 [running]> on host 20958c5a96de
[2022-06-01 19:42:42,713] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T19:42:32.026131+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-01T19:42:32.026131+00:00
[2022-06-01 19:42:42,727] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 48, in upload_to_gcs
    bucket = client.bucket(bucket)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 279, in bucket
    return Bucket(client=self, name=bucket_name, user_project=user_project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 611, in __init__
    name = _validate_name(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 81, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
[2022-06-01 19:42:42,744] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20220601T194232, start_date=20220601T194242, end_date=20220601T194242
[2022-06-01 19:42:42,759] {standard_task_runner.py:92} ERROR - Failed to execute job 118 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 48, in upload_to_gcs
    bucket = client.bucket(bucket)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 279, in bucket
    return Bucket(client=self, name=bucket_name, user_project=user_project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 611, in __init__
    name = _validate_name(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 81, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
[2022-06-01 19:42:42,793] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-01 19:42:42,835] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
